In [1]:
import torch
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [2]:
inputs.shape

torch.Size([6, 3])

In [3]:
inputs.shape[1]

3

In [4]:
# The second input element
x_2 = inputs[1]
# The input embedding size, d=3
d_in = inputs.shape[1]
# The output embedding size, d_out=2
d_out = 2

In [5]:
torch.manual_seed(123)
W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_key   = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)

In [6]:
keys = inputs @ W_key 
values = inputs @ W_value
print("keys.shape:", keys.shape)
print("values.shape:", values.shape)

keys.shape: torch.Size([6, 2])
values.shape: torch.Size([6, 2])


In [7]:
query_2 = x_2 @ W_query 
key_2 = x_2 @ W_key 
value_2 = x_2 @ W_value
print(query_2)

tensor([0.4306, 1.4551])


In [8]:
keys_2 = keys[1]             #Remember that Python starts indexing at 0.
attn_score_22 = query_2.dot(keys_2)
print(attn_score_22)

tensor(1.8524)


In [7]:
torch.manual_seed(123)
dropout = torch.nn.Dropout(0.3)    # We choose a dropout rate of 50%
example = torch.ones(6, 6)      # we create a matrix of 1s.
print(example)
print(dropout(example))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
tensor([[1.4286, 1.4286, 1.4286, 1.4286, 1.4286, 1.4286],
        [1.4286, 1.4286, 1.4286, 0.0000, 1.4286, 1.4286],
        [0.0000, 1.4286, 1.4286, 1.4286, 1.4286, 0.0000],
        [1.4286, 1.4286, 0.0000, 0.0000, 0.0000, 1.4286],
        [1.4286, 0.0000, 0.0000, 1.4286, 0.0000, 1.4286],
        [1.4286, 1.4286, 0.0000, 0.0000, 0.0000, 0.0000]])
